name: hyperbolic
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _python_abi3_support=1.0
  - appnope=0.1.4
  - asttokens=3.0.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - certifi=2025.10.5
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - comm=0.2.3
  - contourpy=1.3.3
  - cpython=3.12.10
  - cycler=0.12.1
  - debugpy=1.8.17
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - filelock=3.18.0
  - fonttools=4.60.1
  - freetype=2.13.3
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - h2=4.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - idna=3.10
  - importlib-metadata=8.7.0
  - ipykernel=7.0.1
  - ipython=9.6.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - jupyter_client=8.6.3
  - jupyter_core=5.9.0
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcxx=20.1.6
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgfortran=5.0.0
  - libgfortran5=14.2.0
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libopenblas=0.3.29
  - libpng=1.6.47
  - libsodium=1.0.20
  - libsqlite=3.49.2
  - libtiff=4.7.0
  - libwebp=1.5.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - markupsafe=3.0.2
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - matplotlib-inline=0.1.7
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - numpy=2.2.6
  - openjpeg=2.5.3
  - openssl=3.5.4
  - packaging=25.0
  - parso=0.8.5
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.2.1
  - pip=25.1.1
  - platformdirs=4.5.0
  - prompt-toolkit=3.0.52
  - psutil=7.1.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.2
  - pyparsing=3.2.5
  - pysocks=1.7.1
  - python=3.12.10
  - python-dateutil=2.9.0.post0
  - python-gil=3.12.10
  - python_abi=3.12
  - pyyaml=6.0.2
  - pyzmq=27.1.0
  - qhull=2020.2
  - readline=8.2
  - requests=2.32.3
  - setuptools=80.8.0
  - six=1.17.0
  - stack_data=0.6.3
  - tk=8.6.13
  - torchaudio=2.5.1
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing_extensions=4.13.2
  - tzdata=2025b
  - unicodedata2=16.0.0
  - urllib3=2.4.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - click==8.3.0
      - fsspec==2025.5.1
      - geoopt==0.5.1
      - hypll==0.1.1
      - joblib==1.5.2
      - nltk==3.9.2
      - regex==2025.10.23
      - scipy==1.16.3
      - sympy==1.13.1
      - torch==2.9.0
      - torchvision==0.24.0
      - tqdm==4.67.1
prefix: /opt/anaconda3/envs/hyperbolic
