name: hyperbolic

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pytorch=2.5.1
  - pytorch-cuda=11.8
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - tqdm
  - networkx
  - sympy
  - pillow
  - requests
  - pyyaml
  - ipython
  - ipykernel
  - jupyter
  - jupyterlab
  - ipywidgets
  - pip

  - pip:
      - geoopt==0.5.1
      - hypll==0.1.1
      - einops==0.8.1
      - fsspec==2025.5.1
      - nltk==3.9.2
      - protobuf==6.33.1
      - pydantic==2.12.5
      - pydantic_core==2.41.5
      - regex==2025.10.23
      - sentry-sdk==2.46.0
      - wandb==0.23.0
      - gitpython==3.1.45
      - gitdb==4.0.12
      - smmap==5.0.2
      - annotated-types==0.7.0
      - typing-inspection==0.4.2
      - click==8.3.0
