name: hyperbolic
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - brotli-python=1.1.0=py312hd8f9ff3_3
  - bzip2=1.0.8=h99b78c6_7
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=1.17.1=py312h0fad829_0
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - cpuonly=2.0=0
  - cpython=3.12.11=py312hd8ed1ab_0
  - filelock=3.18.0=pyhd8ed1ab_0
  - giflib=5.2.2=h93a5062_0
  - gmp=6.3.0=h7bae524_2
  - gmpy2=2.2.1=py312h524cf62_0
  - h2=4.2.0=pyhd8ed1ab_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - idna=3.10=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libblas=3.9.0=31_h10e41b3_openblas
  - libcblas=3.9.0=31_hb3479ef_openblas
  - libcxx=20.1.8=hf598326_1
  - libdeflate=1.24=h5773f1b_0
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.4.6=h1da3d7d_1
  - libfreetype=2.13.3=hce30654_1
  - libfreetype6=2.13.3=h1d14073_1
  - libgfortran=5.0.0=14_2_0_h6c33f7e_103
  - libgfortran5=14.2.0=h6c33f7e_103
  - libjpeg-turbo=3.1.0=h5505292_0
  - liblapack=3.9.0=31_hc9a63f6_openblas
  - liblzma=5.8.1=h39f12f2_2
  - liblzma-devel=5.8.1=h39f12f2_2
  - libopenblas=0.3.29=hea593b9_0
  - libpng=1.6.50=h280e0eb_1
  - libsqlite=3.50.4=h4237e3c_0
  - libtiff=4.7.0=h2f21f7c_5
  - libwebp=1.6.0=hc0253d1_0
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=15.0.7=h7cfbb63_0
  - markupsafe=3.0.2=py312h998013c_1
  - mpc=1.3.1=h8f1351a_1
  - mpfr=4.2.1=hb693164_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - networkx=3.5=pyhe01879c_0
  - numpy=2.3.2=py312h2f38b44_0
  - openjpeg=2.5.3=h889cd5d_1
  - openssl=3.6.0=h5503f6c_0
  - pillow=11.3.0=py312h50aef2c_0
  - pip=24.2=pyh8b19718_1
  - pthread-stubs=0.4=hd74edd7_1002
  - pycparser=2.22=pyh29332c3_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.7=h739c21a_0_cpython
  - python_abi=3.12=8_cp312
  - pytorch=2.5.0=py3.12_0
  - pytorch-mutex=1.0=cpu
  - pyyaml=6.0.2=py312h998013c_2
  - readline=8.2=h1d1bf99_2
  - requests=2.32.4=pyhd8ed1ab_0
  - scikit-learn=1.7.2=py312hc6ded6b_0
  - scipy=1.16.0=py312hcedbd36_0
  - setuptools=80.9.0=pyhff2d567_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=h892fb3f_2
  - torchaudio=2.5.0=py312_cpu
  - torchvision=0.20.0=py312_cpu
  - typing_extensions=4.14.1=pyhe01879c_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - xz=5.8.1=h9a6d368_2
  - xz-gpl-tools=5.8.1=h9a6d368_2
  - xz-tools=5.8.1=h39f12f2_2
  - yaml=0.2.5=h925e9cb_3
  - zstandard=0.23.0=py312hea69d52_2
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.10.0
      - appnope==0.1.4
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - attrs==25.3.0
      - babel==2.17.0
      - beautifulsoup4==4.13.4
      - bleach==6.2.0
      - click==8.3.1
      - comm==0.2.3
      - contourpy==1.3.3
      - cycler==0.12.1
      - debugpy==1.8.15
      - decorator==5.2.1
      - defusedxml==0.7.1
      - einops==0.8.1
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - fonttools==4.59.0
      - fqdn==1.5.1
      - frozenlist==1.7.0
      - fsspec==2025.7.0
      - geoopt==0.5.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - grpcio==1.74.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - hypll==0.1.1
      - ipykernel==6.30.1
      - ipython==9.4.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - jedi==0.19.2
      - json5==0.12.0
      - jsonpointer==3.0.0
      - jsonschema==4.25.0
      - jsonschema-specifications==2025.4.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.6
      - jupyter-server==2.16.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.8
      - lark==1.2.2
      - lightning-utilities==0.15.1
      - markdown==3.8.2
      - matplotlib==3.10.5
      - matplotlib-inline==0.1.7
      - mistune==3.1.3
      - multidict==6.6.3
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - nltk==3.9.2
      - notebook==7.4.5
      - notebook-shim==0.2.4
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.3.1
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - platformdirs==4.3.8
      - prometheus-client==0.22.1
      - prompt-toolkit==3.0.51
      - propcache==0.3.2
      - protobuf==6.31.1
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.3.0
      - pytorch-lightning==2.4.0
      - pytz==2025.2
      - pyzmq==27.0.1
      - referencing==0.36.2
      - regex==2025.11.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.26.0
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sentry-sdk==2.46.0
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.7
      - stack-data==0.6.3
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.17.1
      - tensorboard-data-server==0.7.2
      - terminado==0.18.1
      - tinycss2==1.4.0
      - torchmetrics==1.8.0
      - tornado==6.5.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - types-python-dateutil==2.9.0.20250708
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - uri-template==1.3.0
      - wandb==0.23.0
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - yarl==1.20.1
prefix: /opt/anaconda3/envs/dl2024
